import { OpenApiAxios } from "@web-bee-ru/openapi-axios";
import type { paths } from "./schema/schema"; // generated by openapi-typescript
import Axios from "axios";

const axios = Axios.create({
  baseURL: import.meta.env.VITE_API_URL,
  adapter: "fetch", // strongly recommended (available since axios@1.7.0)
});

const apiClient = new OpenApiAxios<paths, "axios">(axios, {
  validStatus: "axios",
}); // throws like axios (e.g. status 400+, network errors, interceptor errors)
// const api =  new OpenApiAxios<paths>(axios) // same result

export default apiClient;
